### PR TITLE
canceling AnimFrame on layer remove

### PR DESCRIPTION
**Pull request by Nikcharn**
I am using your plugin, and caught the error with forgotten disabling animFrame, when canvas layer was removed.

### CODE REVIEW

**Comment by Sumbera** [comment]
Thanks @Nikcharn !

**Comment by Nikcharn** [comment]
@Sumbera, can you release new version, please?

**Comment by Sumbera** [comment]
done 1.0.4

**Comment by Nikcharn** [comment]
@Sumbera, thanks!

**Pull request merged**
